version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      nextjs-runtime:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "eslint-config-next"
    labels:
      - "dependencies"
      - "security"
